import type { Order, OrderStatus, Pagination } from "./orders";
export type InventoryType = "Increase" | "Decrease" | "Correction";
export interface InventoryProduct { _id: string; name: string; code: string; stock: number; lowStockThreshold: number; unit: string }
export interface InventoryTransaction { _id: string; product: InventoryProduct; type: InventoryType; quantity: number; previousStock: number; newStock: number; reason: string; note: string; createdBy: { _id: string; firstName: string; lastName: string; email: string }; createdAt: string }
export interface InventoryReceipt { _id: string; receiptNumber: string; purchaseOrder?: string | { _id: string; orderNumber: string; supplierName: string }; supplierName: string; deliveryNote: string; receivedAt: string; note: string; items: Array<{ product: string; productName: string; sku: string; unit: string; quantity: number; previousStock: number; newStock: number }>; createdBy: string | { _id: string; firstName: string; lastName: string; email: string }; createdAt: string }
export interface PurchaseOrder { _id: string; orderNumber: string; supplierName: string; supplierReference: string; expectedAt?: string; status: "Ordered" | "PartiallyReceived" | "Received" | "Cancelled"; note: string; items: Array<{ product: string; productName: string; sku: string; unit: string; quantityOrdered: number; quantityReceived: number }>; createdAt: string }
export interface Customer { _id: string; firstName: string; lastName: string; email: string; phone: string; status: "Active" | "Inactive"; createdAt: string; totalOrders?: number; totalSpent?: number }
export interface DashboardData { metrics: { totalProducts: number; activeProducts: number; lowStockProducts: number; outOfStockProducts: number; totalCustomers: number; totalOrders: number; pendingOrders: number; deliveredOrders: number; totalSalesValue: number }; recentOrders: Pick<Order, "_id" | "orderNumber" | "customerName" | "total" | "orderStatus" | "createdAt">[]; orderStatusSummary: { status: OrderStatus; count: number }[]; salesTrend: { date: string; sales: number; orders: number }[]; topSellingProducts: { _id: string; name: string; sku: string; quantity: number; sales: number }[]; lowStockProducts: InventoryProduct[]; recentCustomers: Customer[]; revenueStatuses: string[] }
export interface SalesReport { range: { from: string; to: string; period: string }; revenueStatuses: string[]; summary: { orders: number; grossOrderValue: number; totalSales: number; averageOrderValue: number; deliveredOrderRevenue: number; deliveredOrders: number; cancelledOrders: number }; topProducts: { _id: string; name: string; sku: string; quantity: number; sales: number }[]; salesByPeriod: { date: string; sales: number; orders: number }[] }
export interface CustomerDetails { customer: Customer; addresses: Array<{ _id: string; fullName: string; phone: string; city: string; district: string; addressLine: string; isDefault: boolean }>; orders: Order[]; totals: { totalOrders: number; totalSpent: number }; revenueStatuses: string[] }
export interface Paginated<T> { success: boolean; data: T[]; pagination: Pagination }
