import { Link } from "react-router-dom";
import { useCart } from "../cart/useCart";
import { ErrorState } from "../components/ui/AsyncState";
import { useWishlist } from "../wishlist/useWishlist";
import { currencyFormatter } from "../utils/format";

export function WishlistPage() {
  const wishlist = useWishlist();
  const cart = useCart();
  if (wishlist.loading && !wishlist.wishlist.products.length) return <main className="mx-auto min-h-[60vh] max-w-7xl px-5 py-12"><div className="h-80 animate-pulse rounded-3xl bg-slate-200" /></main>;
  if (wishlist.error && !wishlist.wishlist.products.length) return <main className="mx-auto min-h-[60vh] max-w-7xl px-5 py-12"><ErrorState message={wishlist.error} onRetry={() => void wishlist.refreshWishlist()} /></main>;
  if (!wishlist.wishlist.products.length) return <main className="mx-auto grid min-h-[60vh] max-w-2xl place-items-center px-5 py-16 text-center"><div><div className="text-6xl">♡</div><h1 className="mt-5 text-3xl font-black">Your wishlist is ready</h1><p className="mt-3 text-slate-500">Save products here to find them quickly later.</p><Link className="mt-7 inline-block rounded-xl bg-[#1F88C9] px-6 py-3 font-bold text-white" to="/shop">Discover products</Link></div></main>;
  return <main className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-sm font-bold uppercase tracking-wider text-[#CA7209]">Saved items</p><h1 className="mt-2 text-4xl font-black">Your wishlist</h1></div><button className="text-sm font-bold text-red-600" onClick={() => void wishlist.clearWishlist()} type="button">Clear wishlist</button></div>{wishlist.error && <p className="mt-6 rounded-xl bg-red-50 p-3 text-sm text-red-700">{wishlist.error}</p>}<div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{wishlist.wishlist.products.map((product) => <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white" key={product._id}><Link className="block aspect-[4/3] bg-slate-100" to={`/products/${product._id}`}>{product.images[0] ? <img alt={product.name} className="h-full w-full object-cover" src={product.images[0]} /> : <span className="grid h-full place-items-center text-4xl font-black text-[#1F88C9]/25">BBG</span>}</Link><div className="p-5"><Link className="font-black hover:text-[#1F88C9]" to={`/products/${product._id}`}>{product.name}</Link><p className="mt-2 text-lg font-black">{currencyFormatter.format(product.price)}</p><p className={`mt-2 text-xs font-bold ${product.status === "Active" && product.stock ? "text-emerald-600" : "text-red-600"}`}>{product.status !== "Active" ? "Unavailable" : product.stock ? `${product.stock} available` : "Out of stock"}</p><div className="mt-5 flex gap-2"><button className="flex-1 rounded-xl bg-[#1F88C9] px-4 py-2.5 text-sm font-bold text-white disabled:bg-slate-300" disabled={product.status !== "Active" || !product.stock || cart.busyProductId === product._id} onClick={() => void cart.addToCart(product._id)} type="button">{cart.busyProductId === product._id ? "Adding…" : "Add to cart"}</button><button className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-bold text-red-600" disabled={wishlist.busyProductId === product._id} onClick={() => void wishlist.removeFromWishlist(product._id)} type="button">Remove</button></div></div></article>)}</div></main>;
}
