import { useState } from "react";
import { NavLink, Outlet, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/useAuth";
import { CloseIcon, MenuIcon } from "../components/ui/Icons";

const primary = [{ to: "/admin", label: "Overview", icon: "⌂" }, { to: "/admin/products", label: "Products", icon: "□" }, { to: "/admin/orders", label: "Orders", icon: "◇" }, { to: "/admin/customers", label: "Customers", icon: "○" }, { to: "/admin/reports", label: "Reports", icon: "↗" }];
const inventory = [{ to: "/admin/inventory", label: "Stock overview" }, { to: "/admin/inventory/purchase-orders", label: "Purchase orders" }, { to: "/admin/inventory/receipts", label: "Goods receipts" }, { to: "/admin/inventory/movements", label: "Stock movements" }];

export function AdminLayout() {
  const { user, logout } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [menuOpen, setMenuOpen] = useState(false);
  const current = [...primary, ...inventory].find((item) => item.to === location.pathname)?.label ?? "Administration";
  async function signOut() { await logout(); navigate("/login", { replace: true }); }
  return <div className="min-h-screen bg-slate-50 text-slate-900 lg:grid lg:grid-cols-[272px_minmax(0,1fr)]">
    {menuOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-sky-600/50 lg:hidden" onClick={() => setMenuOpen(false)} type="button" />}
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[272px] -translate-x-full flex-col border-r border-sky-100 bg-white text-slate-800 shadow-2xl shadow-sky-100 transition-transform lg:sticky lg:top-0 lg:h-screen lg:translate-x-0 lg:shadow-none ${menuOpen ? "translate-x-0" : ""}`}>
      <div className="flex h-20 items-center justify-between border-b border-sky-100 px-6"><NavLink className="flex items-center gap-3" to="/admin"><span className="grid size-10 place-items-center rounded-xl bg-sky-500 text-sm font-black text-white shadow-sm">BBG</span><span><strong className="block text-sm tracking-wide text-slate-900">BBG ELECTRONICS</strong><small className="text-[11px] text-slate-500">Operations console</small></span></NavLink><button aria-label="Close menu" className="text-slate-500 lg:hidden" onClick={() => setMenuOpen(false)} type="button"><CloseIcon className="size-6" /></button></div>
      <nav aria-label="Admin navigation" className="flex-1 overflow-y-auto px-4 py-6"><NavGroup items={primary} onNavigate={() => setMenuOpen(false)} /><p className="mb-2 mt-8 px-3 text-[10px] font-bold uppercase tracking-[0.22em] text-orange-500">Inventory management</p><NavGroup items={inventory} onNavigate={() => setMenuOpen(false)} /></nav>
      <div className="border-t border-sky-100 p-4"><div className="rounded-xl bg-sky-50 p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-orange-100 text-xs font-black text-orange-600">{user?.firstName?.[0]}{user?.lastName?.[0]}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{user?.firstName} {user?.lastName}</p><p className="truncate text-xs text-slate-500">{user?.email}</p></div></div><div className="mt-3 flex justify-between border-t border-sky-100 pt-3"><NavLink className="text-xs font-semibold text-sky-600 hover:text-orange-600" to="/">Storefront ↗</NavLink><button className="text-xs font-semibold text-slate-500 hover:text-orange-600" onClick={() => void signOut()} type="button">Sign out</button></div></div></div>
    </aside>
    <div className="min-w-0"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" className="icon-button lg:hidden" onClick={() => setMenuOpen(true)} type="button"><MenuIcon className="size-5" /></button><div><p className="text-xs font-medium text-slate-400">Workspace</p><p className="text-sm font-bold">{current}</p></div></div><span className="hidden items-center gap-2 text-xs font-semibold text-slate-500 sm:flex"><span className="size-2 rounded-full bg-orange-400" /> Administrator workspace</span></header><Outlet /></div>
  </div>;
}
function NavGroup({ items, onNavigate }: { items: Array<{ to: string; label: string; icon?: string }>; onNavigate: () => void }) { return <div className="space-y-1">{items.map((item) => <NavLink className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${isActive ? "bg-sky-50 text-sky-700 ring-1 ring-sky-100" : "text-slate-600 hover:bg-orange-50 hover:text-orange-700"}`} end={item.to === "/admin" || item.to === "/admin/inventory"} key={item.to} onClick={onNavigate} to={item.to}><span className={`grid w-5 place-items-center text-base`}>{item.icon ?? "·"}</span>{item.label}</NavLink>)}</div>; }
