import { type FormEvent, useEffect, useState } from "react";
import { AdminPageHeader } from "./AdminPageHeader";
import { StatusBadge } from "./StatusBadge";
import type { CatalogStatus } from "../../types/catalog";
import { formatApiError } from "../../utils/format";
import { ImageUploadButton } from "./ImageUploadButton";

export interface CatalogEntity { _id: string; name: string; slug: string; description: string; status: CatalogStatus; media: string }
interface Props { noun: "brand" | "category"; load: () => Promise<CatalogEntity[]>; create: (input: EntityInput) => Promise<unknown>; update: (id: string, input: EntityInput) => Promise<unknown>; remove: (id: string) => Promise<void> }
export interface EntityInput { name: string; description: string; media: string; status: CatalogStatus }

export function CatalogEntityManager({ create, load, noun, remove, update }: Props) {
  const [items, setItems] = useState<CatalogEntity[]>([]); const [editing, setEditing] = useState<CatalogEntity | null>(null); const [showForm, setShowForm] = useState(false); const [media, setMedia] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function refresh() { try { setItems(await load()); setError(""); } catch (reason: unknown) { setError(formatApiError(reason)); } }
  useEffect(() => { void load().then(setItems).catch((reason: unknown) => setError(formatApiError(reason))); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const input: EntityInput = { name: String(data.get("name")), description: String(data.get("description")), media, status: String(data.get("status")) as CatalogStatus }; setBusy(true); try { if (editing) await update(editing._id, input); else await create(input); setShowForm(false); setEditing(null); setMedia(""); await refresh(); } catch (reason: unknown) { setError(formatApiError(reason)); } finally { setBusy(false); } }
  async function deleteItem(item: CatalogEntity) { if (!window.confirm(`Delete ${item.name}?`)) return; try { await remove(item._id); await refresh(); } catch (reason: unknown) { setError(formatApiError(reason)); } }
  const title = noun === "brand" ? "Brands" : "Categories";
  return <main className="p-5 sm:p-8"><AdminPageHeader action={<button className="rounded-xl bg-[#1F88C9] px-5 py-3 text-sm font-bold text-white" onClick={() => { setEditing(null); setMedia(""); setShowForm(true); }} type="button">Create {noun}</button>} description={`Create and maintain product ${title.toLowerCase()}.`} title={title} />{error && <p className="mt-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}{showForm && <form className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 sm:grid-cols-2" onSubmit={submit}><input className="rounded-xl border border-slate-300 px-4 py-3 text-sm" defaultValue={editing?.name} name="name" placeholder="Name" required /><select className="rounded-xl border border-slate-300 px-4 py-3 text-sm" defaultValue={editing?.status ?? "Active"} name="status"><option>Active</option><option>Inactive</option></select><div className="sm:col-span-2"><input className="w-full rounded-xl border border-slate-300 px-4 py-3 text-sm" onChange={(event) => setMedia(event.target.value)} placeholder={`${noun === "brand" ? "Logo" : "Image"} URL (optional)`} type="url" value={media} /><div className="mt-3"><ImageUploadButton onUploaded={([url]) => setMedia(url ?? "")} /></div></div><textarea className="rounded-xl border border-slate-300 px-4 py-3 text-sm sm:col-span-2" defaultValue={editing?.description} name="description" placeholder="Description" rows={3} /><div className="flex gap-3 sm:col-span-2"><button className="rounded-xl bg-[#1F88C9] px-5 py-3 text-sm font-bold text-white disabled:opacity-50" disabled={busy} type="submit">{editing ? "Save changes" : `Create ${noun}`}</button><button className="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold" onClick={() => setShowForm(false)} type="button">Cancel</button></div></form>}<div className="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="overflow-x-auto"><table className="w-full min-w-2xl text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Name</th><th>Slug</th><th>Status</th><th className="px-5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item._id}><td className="px-5 py-4 font-bold">{item.name}</td><td className="text-slate-500">{item.slug}</td><td><StatusBadge status={item.status} /></td><td className="px-5 text-right"><button className="mr-4 font-bold text-[#1F88C9]" onClick={() => { setEditing(item); setMedia(item.media); setShowForm(true); }} type="button">Edit</button><button className="font-bold text-red-600" onClick={() => void deleteItem(item)} type="button">Delete</button></td></tr>)}</tbody></table></div>{!items.length && <p className="p-8 text-center text-sm text-slate-500">No {title.toLowerCase()} created yet.</p>}</div></main>;
}
