import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getCustomer, setCustomerStatus } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import { OrderStatusBadge } from "../../components/orders/OrderStatusBadge";
import type { CustomerDetails } from "../../types/admin";
import { currencyFormatter, formatApiError } from "../../utils/format";
export function AdminCustomerDetailsPage() { const { id = "" } = useParams(); const [data, setData] = useState<CustomerDetails>(); const [error, setError] = useState(""); const load = () => void getCustomer(id).then(setData).catch((e: unknown) => setError(formatApiError(e))); useEffect(load, [id]);
  if (error) return <main className="p-8 text-red-700">{error}</main>; if (!data) return <main className="p-8">Loading customer…</main>; const c = data.customer;
  async function toggle() { await setCustomerStatus(id, c.status === "Active" ? "Inactive" : "Active"); load(); }
  return <main className="p-5 sm:p-8"><AdminPageHeader title={`${c.firstName} ${c.lastName}`} description="Customer profile, addresses, and order history." action={<button className="rounded-xl border border-slate-300 bg-white px-4 py-2 font-bold" onClick={() => void toggle()}>{c.status === "Active" ? "Deactivate" : "Activate"}</button>} /><section className="mt-6 grid gap-4 sm:grid-cols-3"><Card label="Status" value={c.status} /><Card label="Total orders" value={data.totals.totalOrders} /><Card label="Total spent" value={currencyFormatter.format(data.totals.totalSpent)} /></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-black">Profile</h2><p className="mt-3">{c.email} · {c.phone || "No phone"}</p><p className="text-sm text-slate-500">Joined {new Date(c.createdAt).toLocaleDateString()}</p></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-black">Addresses</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{data.addresses.map((a) => <address className="rounded-xl border p-4 not-italic" key={a._id}><strong>{a.fullName}{a.isDefault ? " · Default" : ""}</strong><br />{a.addressLine}, {a.district}, {a.city}<br />{a.phone}</address>)}</div></section><section className="mt-6 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-black">Order history</h2><table className="mt-3 w-full min-w-[650px] text-left text-sm"><tbody>{data.orders.map((o) => <tr className="border-t" key={o._id}><td className="py-4"><Link className="font-bold text-[#0ea5e9]" to={`/admin/orders/${o._id}`}>{o.orderNumber}</Link></td><td>{new Date(o.createdAt).toLocaleDateString()}</td><td>{currencyFormatter.format(o.total)}</td><td><OrderStatusBadge value={o.orderStatus} /></td></tr>)}</tbody></table></section><p className="mt-5 text-xs text-slate-500">Total spent includes {data.revenueStatuses.join(", ")} orders only.</p></main>; }
function Card({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-2xl">{value}</strong></div>; }
