import { useEffect, useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { getPurchaseOrder, receivePurchaseOrder } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import type { InventoryReceipt, PurchaseOrder } from "../../types/admin";
import { formatApiError } from "../../utils/format";
export function AdminReceiveStockPage() { const { id = "" } = useParams(); const [order, setOrder] = useState<PurchaseOrder>(); const [quantities, setQuantities] = useState<Record<string, number>>({}); const [receipt, setReceipt] = useState<InventoryReceipt>(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { void getPurchaseOrder(id).then(({ order: value }) => { setOrder(value); setQuantities(Object.fromEntries(value.items.map((item) => [item.product, 0]))); }).catch((reason: unknown) => setError(formatApiError(reason))); }, [id]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const items = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([product, quantity]) => ({ product, quantity })); setSaving(true); try { setReceipt(await receivePurchaseOrder(id, { deliveryNote: String(form.get("deliveryNote")), receivedAt: String(form.get("receivedAt")), note: String(form.get("note")), items })); } catch (reason) { setError(formatApiError(reason)); } finally { setSaving(false); } }
  if (receipt && order) return <main className="p-5 sm:p-8 print:p-0"><div className="mb-5 flex gap-3 print:hidden"><button className="rounded-xl bg-[#0ea5e9] px-5 py-3 font-bold text-white" onClick={() => window.print()}>Print GRN</button><Link className="rounded-xl border bg-white px-5 py-3 font-bold" to="/admin/inventory/purchase-orders">Purchase orders</Link></div><Receipt receipt={receipt} order={order} /></main>;
  if (!order) return <main className="p-8">{error || "Loading purchase order…"}</main>;
  return <main className="p-5 sm:p-8"><AdminPageHeader action={<Link className="rounded-xl border bg-white px-4 py-3 font-bold" to="/admin/inventory/purchase-orders">← Purchase orders</Link>} description={`${order.supplierName} · receive only quantities outstanding on this order.`} eyebrow="Inventory" title={`Receive ${order.orderNumber}`} />{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<form className="mt-6 rounded-2xl bg-white p-6" onSubmit={submit}><div className="grid gap-4 md:grid-cols-2"><Field label="Supplier delivery note"><input name="deliveryNote" required /></Field><Field label="Date received"><input defaultValue={new Date().toISOString().slice(0, 10)} name="receivedAt" required type="date" /></Field></div><h2 className="mt-7 font-black">Purchase-order lines</h2><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-3">Material</th><th>Ordered</th><th>Previously received</th><th>Remaining</th><th>Receive now</th></tr></thead><tbody>{order.items.map((item) => { const remaining = item.quantityOrdered - item.quantityReceived; return <tr className="border-t" key={item.product}><td className="p-3"><strong>{item.productName}</strong><br />{item.sku}</td><td>{item.quantityOrdered} {item.unit}</td><td>{item.quantityReceived}</td><td>{remaining}</td><td><input className="w-32 rounded-lg border px-3 py-2" disabled={!remaining} max={remaining} min="0" onChange={(event) => setQuantities((value) => ({ ...value, [item.product]: Number(event.target.value) }))} type="number" value={quantities[item.product] ?? 0} /></td></tr>; })}</tbody></table></div><Field label="Receiving notes"><textarea name="note" rows={3} /></Field><button className="mt-6 rounded-xl bg-[#0ea5e9] px-6 py-3 font-bold text-white disabled:opacity-50" disabled={saving || !Object.values(quantities).some((value) => value > 0)}>{saving ? "Receiving…" : "Receive and create GRN"}</button></form></main>; }
function Receipt({ receipt, order }: { receipt: InventoryReceipt; order: PurchaseOrder }) { const actor = typeof receipt.createdBy === "string" ? "Administrator" : `${receipt.createdBy.firstName} ${receipt.createdBy.lastName}`; return <article className="mx-auto max-w-4xl bg-white p-8"><header className="flex justify-between border-b-2 border-slate-900 pb-5"><div><h1 className="text-2xl font-black">GOODS RECEIVED NOTE</h1><p>Purchase order: <strong>{order.orderNumber}</strong></p></div><div className="text-right"><strong>{receipt.receiptNumber}</strong><p>{new Date(receipt.receivedAt).toLocaleDateString()}</p></div></header><div className="my-6 grid grid-cols-2"><p>Supplier<br /><strong>{receipt.supplierName}</strong></p><p>Delivery note<br /><strong>{receipt.deliveryNote}</strong></p></div><table className="w-full text-left text-sm"><thead className="border-y bg-slate-50"><tr><th className="p-3">Material</th><th>SKU</th><th>Received</th><th>Previous stock</th><th>New stock</th></tr></thead><tbody>{receipt.items.map((item) => <tr className="border-b" key={item.product}><td className="p-3">{item.productName}</td><td>{item.sku}</td><td><strong>{item.quantity} {item.unit}</strong></td><td>{item.previousStock}</td><td>{item.newStock}</td></tr>)}</tbody></table><p className="mt-6">Notes: {receipt.note || "—"}</p><footer className="mt-16 grid grid-cols-2 gap-16 text-sm"><div className="border-t pt-2">Received by: {actor}</div><div className="border-t pt-2">Verified by / signature</div></footer></article>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="mt-5 block"><span className="mb-2 block text-sm font-bold">{label}</span><div className="[&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:px-4 [&>*]:py-3">{children}</div></label>; }
