import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { createPurchaseOrder, listPurchaseOrders } from "../../api/admin";
import { listProducts } from "../../api/catalog";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import type { PurchaseOrder } from "../../types/admin";
import type { Product } from "../../types/catalog";
import { formatApiError } from "../../utils/format";
interface Line { id: number; product: string; quantity: number }
export function AdminPurchaseOrdersPage() { const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [products, setProducts] = useState<Product[]>([]); const [showForm, setShowForm] = useState(false); const [lines, setLines] = useState<Line[]>([{ id: 1, product: "", quantity: 1 }]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { try { const [o, p] = await Promise.all([listPurchaseOrders(), listProducts({ limit: 100, sort: "name-asc" })]); setOrders(o); setProducts(p.data); } catch (reason) { setError(formatApiError(reason)); } }, []); useEffect(() => { const timeout = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timeout); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); try { await createPurchaseOrder({ supplierName: String(form.get("supplierName")), supplierReference: String(form.get("supplierReference")), expectedAt: String(form.get("expectedAt")) || undefined, note: String(form.get("note")), items: lines.map(({ product, quantity }) => ({ product, quantity })) }); setShowForm(false); setLines([{ id: Date.now(), product: "", quantity: 1 }]); await load(); } catch (reason) { setError(formatApiError(reason)); } finally { setSaving(false); } }
  return <main className="p-5 sm:p-8"><AdminPageHeader action={<button className="rounded-xl bg-[#0ea5e9] px-5 py-3 font-bold text-white" onClick={() => setShowForm(true)}>New purchase order</button>} description="Order materials first, then receive against their outstanding quantities." eyebrow="Inventory" title="Purchase orders" />{error && <p className="mt-5 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
    {showForm && <form className="mt-6 rounded-2xl bg-white p-6" onSubmit={submit}><div className="grid gap-3 md:grid-cols-3"><Input label="Supplier" name="supplierName" required /><Input label="Supplier reference" name="supplierReference" /><Input label="Expected date" name="expectedAt" type="date" /></div><div className="mt-6 flex justify-between"><h2 className="font-black">Ordered materials</h2><button className="font-bold text-[#0ea5e9]" onClick={() => setLines((value) => [...value, { id: Date.now(), product: "", quantity: 1 }])} type="button">+ Add line</button></div>{lines.map((line, index) => <div className="mt-3 grid gap-3 rounded-xl border p-3 md:grid-cols-[50px_1fr_180px_80px]" key={line.id}><strong>#{index + 1}</strong><select className="rounded-xl border px-3" onChange={(event) => setLines((value) => value.map((item) => item.id === line.id ? { ...item, product: event.target.value } : item))} required value={line.product}><option value="">Select material</option>{products.map((product) => <option disabled={lines.some((other) => other.id !== line.id && other.product === product._id)} key={product._id} value={product._id}>{product.name} · {product.code}</option>)}</select><input className="rounded-xl border px-3" min="1" onChange={(event) => setLines((value) => value.map((item) => item.id === line.id ? { ...item, quantity: Number(event.target.value) } : item))} type="number" value={line.quantity} /><button className="text-red-600" disabled={lines.length === 1} onClick={() => setLines((value) => value.filter((item) => item.id !== line.id))} type="button">Remove</button></div>)}<Input label="Notes" name="note" /><div className="mt-5 flex gap-3"><button className="rounded-xl bg-[#0ea5e9] px-5 py-3 font-bold text-white" disabled={saving}>{saving ? "Creating…" : "Create purchase order"}</button><button onClick={() => setShowForm(false)} type="button">Cancel</button></div></form>}
    <div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Purchase order", "Supplier", "Created", "Progress", "Status", "Action"].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{orders.map((order) => { const ordered = order.items.reduce((s, i) => s + i.quantityOrdered, 0); const received = order.items.reduce((s, i) => s + i.quantityReceived, 0); return <tr className="border-t" key={order._id}><td className="px-4 py-4 font-black"><Link className="text-[#0ea5e9]" to={`/admin/inventory/purchase-orders/${order._id}`}>{order.orderNumber}</Link></td><td className="px-4 py-4">{order.supplierName}<br /><small>{order.supplierReference}</small></td><td className="px-4 py-4">{new Date(order.createdAt).toLocaleDateString()}</td><td className="px-4 py-4">{received} / {ordered}</td><td className="px-4 py-4 font-bold">{order.status}</td><td className="px-4 py-4">{!['Received', 'Cancelled'].includes(order.status) ? <Link className="font-bold text-[#0ea5e9]" to={`/admin/inventory/purchase-orders/${order._id}/receive`}>Receive</Link> : <Link className="font-bold text-slate-600" to={`/admin/inventory/purchase-orders/${order._id}`}>View receipts</Link>}</td></tr>; })}</tbody></table></div></main>; }
function Input({ label, name, required, type = "text" }: { label: string; name: string; required?: boolean; type?: string }) { return <label className="mt-4 block"><span className="mb-2 block text-sm font-bold">{label}</span><input className="w-full rounded-xl border px-4 py-3" name={name} required={required} type={type} /></label>; }
