import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { listCustomers } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import type { Customer } from "../../types/admin";
import { currencyFormatter, formatApiError } from "../../utils/format";
export function AdminCustomersPage() { const [customers, setCustomers] = useState<Customer[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  const load = (s = search, st = status) => void listCustomers({ search: s || undefined, status: st || undefined }).then((x) => { setCustomers(x.data); setError(""); }).catch((e: unknown) => setError(formatApiError(e)));
  useEffect(() => { const timeout = window.setTimeout(() => void listCustomers({}).then((x) => setCustomers(x.data)).catch((e: unknown) => setError(formatApiError(e))), 0); return () => window.clearTimeout(timeout); }, []);
  function submit(e: FormEvent) { e.preventDefault(); load(); }
  return <main className="p-5 sm:p-8"><AdminPageHeader title="Customers" description="Customer accounts and delivered-order lifetime value." /><form className="mt-6 flex flex-wrap gap-3 rounded-2xl bg-white p-4" onSubmit={submit}><input className="min-w-64 flex-1 rounded-xl border px-4 py-2.5" onChange={(e) => setSearch(e.target.value)} placeholder="Name, email, or phone" value={search} /><select className="rounded-xl border px-4" onChange={(e) => setStatus(e.target.value)} value={status}><option value="">All statuses</option><option>Active</option><option>Inactive</option></select><button className="rounded-xl bg-[#0ea5e9] px-5 font-bold text-white">Search</button></form>{error && <p className="mt-4 text-red-700">{error}</p>}<div className="mt-6 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50"><tr>{["Customer", "Contact", "Status", "Orders", "Total spent", "Joined", ""].map((h) => <th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{customers.map((c) => <tr className="border-t" key={c._id}><td className="px-4 py-4 font-bold">{c.firstName} {c.lastName}</td><td className="px-4 py-4">{c.email}<br /><small>{c.phone || "No phone"}</small></td><td className="px-4 py-4">{c.status}</td><td className="px-4 py-4">{c.totalOrders}</td><td className="px-4 py-4 font-bold">{currencyFormatter.format(c.totalSpent ?? 0)}</td><td className="px-4 py-4">{new Date(c.createdAt).toLocaleDateString()}</td><td><Link className="font-bold text-[#0ea5e9]" to={`/admin/customers/${c._id}`}>View</Link></td></tr>)}</tbody></table></div></main>; }
