import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { getPurchaseOrder } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import type { InventoryReceipt, PurchaseOrder } from "../../types/admin";
import { formatApiError } from "../../utils/format";
export function AdminPurchaseOrderDetailsPage() { const { id = "" } = useParams(); const [order, setOrder] = useState<PurchaseOrder>(); const [receipts, setReceipts] = useState<InventoryReceipt[]>([]); const [error, setError] = useState(""); useEffect(() => { void getPurchaseOrder(id).then((result) => { setOrder(result.order); setReceipts(result.receipts); }).catch((reason: unknown) => setError(formatApiError(reason))); }, [id]); if (error) return <main className="p-8 text-red-700">{error}</main>; if (!order) return <main className="p-8">Loading purchase order…</main>;
  const ordered = order.items.reduce((sum, item) => sum + item.quantityOrdered, 0); const received = order.items.reduce((sum, item) => sum + item.quantityReceived, 0);
  return <main className="p-5 sm:p-8"><AdminPageHeader action={!['Received', 'Cancelled'].includes(order.status) ? <Link className="rounded-xl bg-[#0ea5e9] px-5 py-3 font-bold text-white" to={`/admin/inventory/purchase-orders/${order._id}/receive`}>Receive delivery</Link> : undefined} description={`${order.supplierName} · ${received} of ${ordered} units received`} eyebrow="Purchase order" title={order.orderNumber} /><section className="mt-6 grid gap-4 sm:grid-cols-3"><Card label="Status" value={order.status} /><Card label="Supplier reference" value={order.supplierReference || "—"} /><Card label="Receipts" value={receipts.length} /></section><section className="mt-6 overflow-x-auto rounded-2xl bg-white p-5"><h2 className="font-black">Ordered materials</h2><table className="mt-3 w-full min-w-[650px] text-left text-sm"><thead><tr><th className="py-3">Material</th><th>SKU</th><th>Ordered</th><th>Received</th><th>Remaining</th></tr></thead><tbody>{order.items.map((item) => <tr className="border-t" key={item.product}><td className="py-3 font-bold">{item.productName}</td><td>{item.sku}</td><td>{item.quantityOrdered} {item.unit}</td><td>{item.quantityReceived}</td><td className="font-bold">{item.quantityOrdered - item.quantityReceived}</td></tr>)}</tbody></table></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-black">Goods received notes</h2>{receipts.map((receipt) => <div className="mt-3 flex items-center justify-between border-t pt-3" key={receipt._id}><span><strong>{receipt.receiptNumber}</strong><br /><small>{new Date(receipt.receivedAt).toLocaleDateString()} · {receipt.deliveryNote || "No delivery reference"}</small></span><Link className="font-bold text-[#0ea5e9]" to={`/admin/inventory/receipts/${receipt._id}`}>View / print</Link></div>)}{!receipts.length && <p className="mt-3 text-sm text-slate-500">No deliveries received against this order.</p>}</section></main>; }
function Card({ label, value }: { label: string; value: string | number }) { return <div className="rounded-2xl bg-white p-5"><p className="text-sm text-slate-500">{label}</p><strong className="mt-2 block text-xl">{value}</strong></div>; }
