import { useEffect, useState, type FormEvent } from "react";
import { getSalesReport } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import { MetricCard } from "../../components/admin/MetricCard";
import { SalesBars } from "../../components/admin/SalesBars";
import type { SalesReport } from "../../types/admin";
import { currencyFormatter, formatApiError } from "../../utils/format";
export function AdminReportsPage() { const [period, setPeriod] = useState("30d"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [data, setData] = useState<SalesReport>(); const [error, setError] = useState(""); const load = () => void getSalesReport({ period, from: period === "custom" ? from : undefined, to: period === "custom" ? to : undefined }).then(setData).catch((e: unknown) => setError(formatApiError(e))); useEffect(() => { const timeout = window.setTimeout(() => void getSalesReport({ period: "30d" }).then(setData).catch((e: unknown) => setError(formatApiError(e))), 0); return () => window.clearTimeout(timeout); }, []); function submit(e: FormEvent) { e.preventDefault(); load(); }
  return <main className="p-5 sm:p-8"><AdminPageHeader title="Sales reports" description="Order-based reporting with delivered orders recognized as revenue." /><form className="mt-6 flex flex-wrap gap-3 rounded-2xl bg-white p-4" onSubmit={submit}><select className="rounded-xl border px-3 py-2" onChange={(e) => setPeriod(e.target.value)} value={period}><option value="today">Today</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="month">This Month</option><option value="custom">Custom Date Range</option></select>{period === "custom" && <><input className="rounded-xl border px-3" onChange={(e) => setFrom(e.target.value)} required type="date" value={from} /><input className="rounded-xl border px-3" onChange={(e) => setTo(e.target.value)} required type="date" value={to} /></>}<button className="rounded-xl bg-[#0ea5e9] px-5 py-2 font-bold text-white">Apply</button></form>{error && <p className="mt-4 text-red-700">{error}</p>}{data && <><section className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label="Total sales" value={currencyFormatter.format(data.summary.totalSales)} tone="green" /><MetricCard label="Number of orders" value={data.summary.orders} /><MetricCard label="Average order value" value={currencyFormatter.format(data.summary.averageOrderValue)} /><MetricCard label="Delivered revenue" value={currencyFormatter.format(data.summary.deliveredOrderRevenue)} tone="green" /><MetricCard label="Cancelled orders" value={data.summary.cancelledOrders} tone="red" /></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-black">Sales by day</h2><SalesBars data={data.salesByPeriod} /></section><section className="mt-6 rounded-2xl bg-white p-5"><h2 className="font-black">Top products</h2><div className="mt-3 divide-y">{data.topProducts.map((p) => <div className="flex justify-between py-3" key={p._id}><span>{p.name} · {p.sku}</span><strong>{p.quantity} units · {currencyFormatter.format(p.sales)}</strong></div>)}</div></section><p className="mt-5 text-xs text-slate-500">Revenue statuses: {data.revenueStatuses.join(", ")}. Average order value uses all orders in the selected range.</p></>}</main>; }
