import { useEffect, useState, type FormEvent } from "react";
import { Link } from "react-router-dom";
import { listGoodsReceipts } from "../../api/admin";
import { AdminPageHeader } from "../../components/admin/AdminPageHeader";
import type { InventoryReceipt } from "../../types/admin";
import { formatApiError } from "../../utils/format";

function initialRange() { const to = new Date(); const from = new Date(to.getFullYear(), to.getMonth(), 1); return { from: from.toISOString().slice(0, 10), to: to.toISOString().slice(0, 10) }; }
export function AdminGoodsReceiptsRegisterPage() {
  const defaults = initialRange(); const [from, setFrom] = useState(defaults.from); const [to, setTo] = useState(defaults.to); const [applied, setApplied] = useState(defaults); const [receipts, setReceipts] = useState<InventoryReceipt[]>([]); const [error, setError] = useState("");
  useEffect(() => { const timeout = window.setTimeout(() => void listGoodsReceipts(applied.from, applied.to).then(setReceipts).catch((reason: unknown) => setError(formatApiError(reason))), 0); return () => window.clearTimeout(timeout); }, [applied]);
  function submit(event: FormEvent) { event.preventDefault(); setApplied({ from, to }); }
  const totalLines = receipts.reduce((sum, receipt) => sum + receipt.items.length, 0); const totalUnits = receipts.reduce((sum, receipt) => sum + receipt.items.reduce((lineSum, item) => lineSum + item.quantity, 0), 0);
  return <main className="p-5 sm:p-8 print:bg-white print:p-0"><div className="print:hidden"><AdminPageHeader action={<button className="rounded-xl bg-[#0ea5e9] px-5 py-3 font-bold text-white disabled:opacity-40" disabled={!receipts.length} onClick={() => window.print()}>Print period register</button>} description="Select a receipt period, review its GRNs, and print the register." eyebrow="Inventory" title="Goods receipts register" /><form className="mt-6 flex flex-wrap gap-3 rounded-2xl bg-white p-4" onSubmit={submit}><label><span className="mr-2 text-sm font-bold">From</span><input className="rounded-xl border px-3 py-2" max={to} onChange={(event) => setFrom(event.target.value)} required type="date" value={from} /></label><label><span className="mr-2 text-sm font-bold">To</span><input className="rounded-xl border px-3 py-2" min={from} onChange={(event) => setTo(event.target.value)} required type="date" value={to} /></label><button className="rounded-xl bg-slate-900 px-5 py-2 font-bold text-white">Apply period</button></form></div>
    <article className="mt-6 rounded-2xl bg-white p-6 print:mt-0 print:rounded-none"><header className="flex justify-between border-b-2 border-slate-900 pb-5"><div><h1 className="text-2xl font-black">GOODS RECEIPTS REGISTER</h1><p className="text-sm">BBG Inventory</p></div><div className="text-right text-sm"><strong>{new Date(`${applied.from}T00:00:00`).toLocaleDateString()} – {new Date(`${applied.to}T00:00:00`).toLocaleDateString()}</strong><p>{receipts.length} GRNs · {totalLines} lines · {totalUnits} units</p></div></header>{error && <p className="mt-4 text-red-700 print:hidden">{error}</p>}<table className="mt-5 w-full min-w-[760px] text-left text-sm"><thead className="border-y bg-slate-50"><tr><th className="p-3">Date</th><th>GRN</th><th>Purchase order</th><th>Supplier</th><th>Delivery note</th><th>Lines</th><th>Units</th><th className="print:hidden">Action</th></tr></thead><tbody>{receipts.map((receipt) => { const po = typeof receipt.purchaseOrder === "object" ? receipt.purchaseOrder : undefined; const units = receipt.items.reduce((sum, item) => sum + item.quantity, 0); return <tr className="border-b" key={receipt._id}><td className="p-3">{new Date(receipt.receivedAt).toLocaleDateString()}</td><td className="font-bold">{receipt.receiptNumber}</td><td>{po?.orderNumber ?? "—"}</td><td>{receipt.supplierName}</td><td>{receipt.deliveryNote || "—"}</td><td>{receipt.items.length}</td><td className="font-bold">{units}</td><td className="print:hidden"><Link className="font-bold text-[#0ea5e9]" to={`/admin/inventory/receipts/${receipt._id}`}>View / print</Link></td></tr>; })}</tbody></table>{!receipts.length && <p className="py-10 text-center text-sm text-slate-500">No goods receipts in this period.</p>}<footer className="mt-16 hidden grid-cols-2 gap-16 text-sm print:grid"><div className="border-t pt-2">Prepared by / signature</div><div className="border-t pt-2">Verified by / signature</div></footer></article>
  </main>;
}
